yarnPath: '.yarn/releases/yarn-berry.cjs'

packageExtensions:
  react-scripts@*:
    dependencies:
      esbuild-loader: '*'
      eslint-plugin-prefer-arrow: '*'
      eslint-plugin-react-app: '*'
  react-spring@*:
    dependencies:
      react-dom: '*'
  styled-components@*:
    dependencies:
      babel-plugin-macros: '*'
      react-is: '*'
