version: '3'

services:
  web:
    build: .
    environment:
      - VERSION=1.1.0
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:figma-chat.ph1p.dev

    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
