version: '3'

services:
  figmachat:
    build: .
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.figmachat.tls'
      - 'traefik.http.routers.figmachat.tls.certresolver=letsencryptresolver'
      - 'traefik.http.services.figmachat.loadbalancer.server.port=80'
      - 'traefik.http.routers.figmachat.rule=Host(`figma-chat.ph1p.dev`)'
      - 'traefik.http.routers.figmachat.middlewares=sslheader@docker'
    environment:
      - PORT=80
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
