name: Build Figma-Chat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16
        uses: actions/setup-node@main
        with:
          node-version: 16

      - name: yarn install
        run: yarn install

      - name: yarn lint
        run: yarn lint

      - name: yarn build
        run: yarn build:plugin && yarn build:server && yarn build:web
